name: RL_dominion
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - gymnasium>=0.26.3
  - numpy
  - pip  # Ensure pip is installed in the environment
  - pip:
      - -e ./external/pydominion  # Install pydominion as editable from your local submodule path
