name: RL_dominion
channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - gymnasium>=0.26.3
  - numpy
  - pip
  - pip:
      - tensorboard # For logging
      - rl_zoo3 # Could be used to tune hyperparameters
      - stable-baselines3  # PPO and RL algorithms
      - sb3-contrib  # Maskable PPO
      - -e ./external/pydominion  # Install pydominion as editable
      - typing-extensions  # Typing support for Optional, List, etc.
      - logging  # Ensure logging is available
